import Head from "next/head"
import About from "../components/About"
import Banner from "../components/Banner"
import Certifications from "../components/Certifications"
import Contact from "../components/Contact"
import CreativePortfolio from "../components/CreativePortfolio"
import LatestNews from "../components/LatestNews"
import Testimonials from "../components/Testimonials"
import WatchVedio from "../components/WatchVedio"
import styles from '../styles/HomePage.module.css'
const HomePage = () => {
  return (
    <>
     <Head>
        <title>Personal Portfolio Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <Banner/>
       <main className={styles.main}>
       <About/>
       <CreativePortfolio/>
      </main>
       <WatchVedio/>
       <Testimonials/>
       <section className={styles.main}>
       <LatestNews/>
       <Certifications/>
       </section>
       <Contact/>
    </>
  )
}

export default HomePage